//Falcon2-11B DATASET v1.0 Category: Hotel Management System ; Style: puzzling
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

int main() {
  // Puzzle 1: What is the name of the hotel?
  char hotelName[100];
  printf("What is the name of the hotel?\n");
  scanf("%s", hotelName);
  printf("The name of the hotel is %s.\n", hotelName);

  // Puzzle 2: What is the capacity of the hotel?
  int capacity;
  printf("What is the capacity of the hotel?\n");
  scanf("%d", &capacity);
  printf("The capacity of the hotel is %d.\n", capacity);

  // Puzzle 3: What is the current occupancy of the hotel?
  int occupancy;
  printf("What is the current occupancy of the hotel?\n");
  scanf("%d", &occupancy);
  printf("The current occupancy of the hotel is %d.\n", occupancy);

  // Puzzle 4: What is the average guest rating of the hotel?
  float rating;
  printf("What is the average guest rating of the hotel?\n");
  scanf("%f", &rating);
  printf("The average guest rating of the hotel is %f.\n", rating);

  // Puzzle 5: What is the most popular room type in the hotel?
  char roomType[100];
  printf("What is the most popular room type in the hotel?\n");
  scanf("%s", roomType);
  printf("The most popular room type in the hotel is %s.\n", roomType);

  // Puzzle 6: What is the average duration of stay for guests?
  int duration;
  printf("What is the average duration of stay for guests?\n");
  scanf("%d", &duration);
  printf("The average duration of stay for guests is %d.\n", duration);

  // Puzzle 7: What is the total revenue generated by the hotel?
  float revenue;
  printf("What is the total revenue generated by the hotel?\n");
  scanf("%f", &revenue);
  printf("The total revenue generated by the hotel is $%.2f.\n", revenue);

  return 0;
}