//Falcon-180B DATASET v1.0 Category: Fibonacci Sequence Visualizer ; Style: multi-threaded
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

#define MAX_THREADS 100
#define MAX_NUMBERS 1000

int numbers[MAX_NUMBERS];
int num_threads = 0;

void *generate_fibonacci(void *param) {
    int start = *(int *) param;
    int end = start + MAX_NUMBERS / num_threads;

    for (int i = start; i < end; i++) {
        if (numbers[i] == 0) {
            numbers[i] = i;
        } else {
            numbers[i] = numbers[i - 1] + numbers[i - 2];
        }
    }

    return NULL;
}

int main(int argc, char *argv[]) {
    if (argc!= 2) {
        printf("Usage: %s <number of threads>\n", argv[0]);
        return 1;
    }

    num_threads = atoi(argv[1]);

    pthread_t threads[MAX_THREADS];
    int thread_ids[MAX_THREADS];

    for (int i = 0; i < num_threads; i++) {
        int start = i * MAX_NUMBERS / num_threads;
        int end = (i == num_threads - 1)? MAX_NUMBERS : (i + 1) * MAX_NUMBERS / num_threads;

        pthread_create(&threads[i], NULL, generate_fibonacci, &start);
        thread_ids[i] = i;
    }

    for (int i = 0; i < num_threads; i++) {
        pthread_join(threads[i], NULL);
    }

    printf("Fibonacci sequence generated by %d threads:\n", num_threads);
    for (int i = 0; i < MAX_NUMBERS; i++) {
        printf("%d ", numbers[i]);
    }

    return 0;
}