//GEMINI-pro DATASET v1.0 Category: Digital Auction System ; Style: recursive
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Structure to represent an item
typedef struct item {
    int id;             // Unique identifier for the item
    char *name;         // Name of the item
    float reserve_price; // Minimum price at which the item can be sold
    float current_bid;  // Current highest bid for the item
    struct item *next;   // Pointer to the next item in the list
} item;

// Structure to represent an auction
typedef struct auction {
    item *head;         // Pointer to the first item in the auction
    int num_items;      // Number of items in the auction
    float total_revenue; // Total revenue generated by the auction
} auction;

// Function to create a new item
item *create_item(int id, char *name, float reserve_price) {
    item *new_item = malloc(sizeof(item));
    new_item->id = id;
    new_item->name = strdup(name);
    new_item->reserve_price = reserve_price;
    new_item->current_bid = 0.0;
    new_item->next = NULL;
    return new_item;
}

// Function to add an item to an auction
void add_item(auction *auction, item *item) {
    if (auction->head == NULL) {
        auction->head = item;
    } else {
        item->next = auction->head;
        auction->head = item;
    }
    auction->num_items++;
}

// Function to print an item
void print_item(item *item) {
    printf("Item ID: %d\n", item->id);
    printf("Item Name: %s\n", item->name);
    printf("Reserve Price: %.2f\n", item->reserve_price);
    printf("Current Bid: %.2f\n\n", item->current_bid);
}

// Function to print an auction
void print_auction(auction *auction) {
    item *current_item = auction->head;
    while (current_item != NULL) {
        print_item(current_item);
        current_item = current_item->next;
    }
    printf("Total Revenue: %.2f\n", auction->total_revenue);
}

// Function to get the highest bid for an item
float get_highest_bid(item *item) {
    return item->current_bid;
}

// Function to place a bid on an item
void place_bid(item *item, float bid) {
    if (bid >= item->reserve_price) {
        item->current_bid = bid;
    }
}

// Function to run the auction
void run_auction(auction *auction) {
    item *current_item = auction->head;
    while (current_item != NULL) {
        printf("Current Item: %s\n", current_item->name);
        float highest_bid = get_highest_bid(current_item);
        printf("Highest Bid: %.2f\n", highest_bid);
        float new_bid;
        printf("Enter a new bid (or 0 to pass): ");
        scanf("%f", &new_bid);
        if (new_bid > 0.0) {
            place_bid(current_item, new_bid);
        }
        current_item = current_item->next;
    }
    // Calculate the total revenue generated by the auction
    auction->total_revenue = 0.0;
    current_item = auction->head;
    while (current_item != NULL) {
        auction->total_revenue += current_item->current_bid;
        current_item = current_item->next;
    }
}

// Function to free the memory allocated for an item
void free_item(item *item) {
    free(item->name);
    free(item);
}

// Function to free the memory allocated for an auction
void free_auction(auction *auction) {
    item *current_item = auction->head;
    while (current_item != NULL) {
        item *next_item = current_item->next;
        free_item(current_item);
        current_item = next_item;
    }
    free(auction);
}

// Main function
int main() {
    // Create a new auction
    auction *auction = malloc(sizeof(auction));
    auction->head = NULL;
    auction->num_items = 0;
    auction->total_revenue = 0.0;

    // Add items to the auction
    add_item(auction, create_item(1, "Painting", 100.0));
    add_item(auction, create_item(2, "Sculpture", 200.0));
    add_item(auction, create_item(3, "Vase", 50.0));

    // Print the auction
    print_auction(auction);

    // Run the auction
    run_auction(auction);

    // Print the auction results
    print_auction(auction);

    // Free the memory allocated for the auction
    free_auction(auction);

    return 0;
}