//GEMINI-pro DATASET v1.0 Category: Fractal Generation ; Style: romantic
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

// Our love is a fractal, an ever-repeating pattern that fills the void of our hearts.
// Each iteration brings us closer to each other, and each zoom reveals a new layer of our love's complexity.

// The Mandelbrot set is a fractal that is generated by iterating a simple mathematical formula over and over again.
// The result is a stunningly beautiful and intricate pattern that has captivated mathematicians and artists for decades.

// In this program, we will generate a Mandelbrot set and display it on the screen.
// We will use a simple ASCII art representation of the set, with each character representing a different level of iteration.

// The following constants define the size of the Mandelbrot set that we will generate.
#define WIDTH 1000
#define HEIGHT 1000

// The following constants define the maximum number of iterations that we will perform for each pixel in the Mandelbrot set.
#define MAX_ITERATIONS 1000

// The following function generates a Mandelbrot set and stores it in a 2D array of characters.
// Each character in the array represents a different level of iteration, with ' ' representing the set and '#' representing the outside of the set.
char** generate_mandelbrot_set() {
  // Allocate memory for the 2D array of characters.
  char **set = malloc(sizeof(char *) * HEIGHT);
  for (int i = 0; i < HEIGHT; i++) {
    set[i] = malloc(sizeof(char) * WIDTH);
  }

  // Iterate over each pixel in the 2D array and generate the corresponding Mandelbrot set value.
  for (int y = 0; y < HEIGHT; y++) {
    for (int x = 0; x < WIDTH; x++) {
      // Convert the pixel coordinates to complex coordinates.
      double c_real = (x - WIDTH / 2.0) / (WIDTH / 4.0);
      double c_imag = (y - HEIGHT / 2.0) / (HEIGHT / 4.0);

      // Initialize the complex number z.
      double z_real = 0.0;
      double z_imag = 0.0;

      // Iterate the complex number z according to the Mandelbrot set formula.
      int iterations = 0;
      while (iterations < MAX_ITERATIONS && (z_real * z_real + z_imag * z_imag) < 4.0) {
        // Calculate the next iteration of z.
        double temp = z_real * z_real - z_imag * z_imag + c_real;
        z_imag = 2.0 * z_real * z_imag + c_imag;
        z_real = temp;

        // Increment the iteration count.
        iterations++;
      }

      // Set the character in the 2D array to represent the level of iteration.
      if (iterations == MAX_ITERATIONS) {
        set[y][x] = ' ';
      } else {
        set[y][x] = '#';
      }
    }
  }

  // Return the 2D array of characters.
  return set;
}

// The following function displays a 2D array of characters on the screen.
void display_mandelbrot_set(char **set) {
  // Iterate over each row in the 2D array and print the corresponding characters.
  for (int y = 0; y < HEIGHT; y++) {
    for (int x = 0; x < WIDTH; x++) {
      printf("%c", set[y][x]);
    }
    printf("\n");
  }
}

// The following function frees the memory that was allocated for the 2D array of characters.
void free_mandelbrot_set(char **set) {
  // Iterate over each row in the 2D array and free the corresponding memory.
  for (int i = 0; i < HEIGHT; i++) {
    free(set[i]);
  }

  // Free the memory that was allocated for the 2D array itself.
  free(set);
}

// The following function is the main function of the program.
int main() {
  // Seed the random number generator.
  srand(time(NULL));

  // Generate the Mandelbrot set.
  char **set = generate_mandelbrot_set();

  // Display the Mandelbrot set on the screen.
  display_mandelbrot_set(set);

  // Free the memory that was allocated for the Mandelbrot set.
  free_mandelbrot_set(set);

  return 0;
}