//GPT-4o-mini DATASET v1.0 Category: Huffman Coding Implementation ; Style: unmistakable
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_TREE_HEIGHT 100

// Node structure for Huffman Tree
struct Node {
    char character;
    unsigned frequency;
    struct Node *left, *right;
};

// Function to create a new node
struct Node* createNode(char character, unsigned frequency) {
    struct Node* temp = (struct Node*)malloc(sizeof(struct Node));
    temp->character = character;
    temp->frequency = frequency;
    temp->left = temp->right = NULL;
    return temp;
}

// Function to build the Huffman tree
struct Node* buildHuffmanTree(char characters[], int frequencies[], int size) {
    struct Node* left, *right, *top;
    int i;
    
    while (size > 1) {
        // Find the two nodes with the lowest frequency
        unsigned min1 = 0, min2 = 1;
        if (frequencies[min1] > frequencies[min2]) {
            min1 = 1;
            min2 = 0;
        }
        
        for (i = 2; i < size; i++) {
            if (frequencies[i] < frequencies[min1]) {
                min2 = min1;
                min1 = i;
            } else if (frequencies[i] < frequencies[min2]) {
                min2 = i;
            }
        }
        
        left = createNode(characters[min1], frequencies[min1]);
        right = createNode(characters[min2], frequencies[min2]);
        
        top = createNode('$', frequencies[min1] + frequencies[min2]);
        top->left = left;
        top->right = right;
        
        characters[min1] = top->character;
        frequencies[min1] = top->frequency;
        
        for (i = min2; i < size - 1; i++) {
            characters[i] = characters[i + 1];
            frequencies[i] = frequencies[i + 1];
        }
        
        size--;
    }
    
    return createNode(characters[0], frequencies[0]);
}

// Function to print the codes generated by the Huffman tree
void printCodes(struct Node* root, int arr[], int top) {
    if (root->left) {
        arr[top] = 0;
        printCodes(root->left, arr, top + 1);
    }
    
    if (root->right) {
        arr[top] = 1;
        printCodes(root->right, arr, top + 1);
    }
    
    if (!root->left && !root->right) {
        printf("%c: ", root->character);
        for (int i = 0; i < top; i++)
            printf("%d", arr[i]);
        printf("\n");
    }
}

// Function to clean up memory for the Huffman tree
void freeTree(struct Node* root) {
    if (root) {
        freeTree(root->left);
        freeTree(root->right);
        free(root);
    }
}

// Driver program to test the above functions
int main() {
    char characters[] = { 'a', 'b', 'c', 'd', 'e', 'f' };
    int frequencies[] = { 5, 9, 12, 13, 16, 45 };
    int size = sizeof(characters) / sizeof(characters[0]);
    
    struct Node* root = buildHuffmanTree(characters, frequencies, size);
    
    int arr[MAX_TREE_HEIGHT], top = 0;
    printf("Huffman Codes:\n");
    printCodes(root, arr, top);
    
    freeTree(root);
    
    return 0;
}