//MISTRAL-7B DATASET v1.0 Category: Pixel Art Generator ; Style: ultraprecise
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <math.h>

#define WIDTH 32
#define HEIGHT 32
#define BPP 3
#define BUF_SIZE (WIDTH * HEIGHT * BPP)

typedef struct {
    unsigned char r;
    unsigned char g;
    unsigned char b;
} pixel_t;

void generate_pixel_art(pixel_t *pixels) {
    int x, y, i;

    for (x = 0; x < WIDTH; x++) {
        for (y = 0; y < HEIGHT; y++) {
            i = y * WIDTH + x;
            pixels[i].r = x < WIDTH / 2 ? 255 : 0;
            pixels[i].g = y < HEIGHT / 2 ? 255 : 0;
            pixels[i].b = (x + y) % 2 == 0 ? 255 : 0;
        }
    }
}

int main() {
    int fd, i;
    void *buffer;
    pixel_t *pixels;

    fd = open("output.pgm", O_CREAT | O_WRONLY | O_TRUNC, 0644);
    if (fd < 0) {
        perror("open");
        exit(EXIT_FAILURE);
    }

    pixels = mmap(NULL, BUF_SIZE, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
    if (pixels == MAP_FAILED) {
        perror("mmap");
        close(fd);
        exit(EXIT_FAILURE);
    }

    generate_pixel_art(pixels);

    fprintf(stdout, "P5\n%d %d\n255\n", WIDTH, HEIGHT);
    fprintf(stdout, "%s\n", "generated by my unique C pixel art generator");

    write(fileno(stdin), "P6\n", 3);
    write(fileno(stdin), "binary\n", 6);
    write(fileno(stdin), "640\n320\n255\n", 13);

    for (i = 0; i < WIDTH * HEIGHT * BPP; i += BPP) {
        write(fileno(stdin), &pixels[i].b, 1);
        write(fileno(stdin), &pixels[i].g, 1);
        write(fileno(stdout), &pixels[i].r, 1);
    }

    munmap(pixels, BUF_SIZE);
    close(fd);

    return EXIT_SUCCESS;
}