//Falcon-180B DATASET v1.0 Category: Color Code Converter ; Style: Ken Thompson
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_LINE_LENGTH 1000
#define MAX_COLOR_NAMES 100

typedef struct {
    char *name;
    char hex[8];
} color_t;

color_t colors[MAX_COLOR_NAMES];
int num_colors = 0;

void add_color(char *name, char *hex) {
    if (num_colors >= MAX_COLOR_NAMES) {
        printf("Error: maximum number of colors reached\n");
        exit(1);
    }
    strncpy(colors[num_colors].name, name, 32);
    strncpy(colors[num_colors].hex, hex, 8);
    num_colors++;
}

int main(int argc, char **argv) {
    if (argc < 2) {
        printf("Usage: %s <input_file>\n", argv[0]);
        return 1;
    }

    FILE *fp = fopen(argv[1], "r");
    if (fp == NULL) {
        printf("Error: could not open input file\n");
        return 1;
    }

    char line[MAX_LINE_LENGTH];
    while (fgets(line, MAX_LINE_LENGTH, fp)!= NULL) {
        int len = strlen(line);
        if (line[len - 1] == '\n') {
            line[len - 1] = '\0';
        }

        char *token = strtok(line, " ");
        while (token!= NULL) {
            if (strncmp(token, "#define", 8) == 0) {
                char *name = strtok(NULL, " ");
                char *hex = strtok(NULL, " ");
                if (name!= NULL && hex!= NULL) {
                    add_color(name, hex);
                }
            }
            token = strtok(NULL, " ");
        }
    }

    fclose(fp);

    printf("/* Generated by %s */\n\n", argv[0]);
    printf("#include <stdio.h>\n");
    printf("#include <stdlib.h>\n");
    printf("#include <string.h>\n\n");

    for (int i = 0; i < num_colors; i++) {
        printf("#define %s \"%s\"\n", colors[i].name, colors[i].hex);
    }

    return 0;
}